### ISSUE TITLE
Repo does not seem to work

### ISSUE THREAD

**Issue by nopper** [takawitter/repo#1]
I am trying to include one of your library (trie4j) inside my project but the maven repo hosted on github seems to be not properly configured:
1. The link to the maven repo is broken, specifically the `mvn-repo` branch does not seem to exist. I have to use the branch to master and use the link `https://raw.github.com/takawitter/repo/master/` intead of `https://raw.github.com/takawitter/repo/mvn-repo/`
2. The jar hosted on the github repo project does not contain any code at all. Indeed opening the jar of the latest jar you can see that nothing is inside:

```
$ jar -tf trie4j-0.5.0-20140116.011053-3.jar
META-INF/
META-INF/MANIFEST.MF
META-INF/maven/
META-INF/maven/org.trie4j/
META-INF/maven/org.trie4j/trie4j/
META-INF/maven/org.trie4j/trie4j/pom.xml
META-INF/maven/org.trie4j/trie4j/pom.properties
```

For the moment I am registering the snapshot jar to my local m2 repository with the command:

```
$ mvn install:install-file -Dfile=trie4j-SNAPSHOT.jar -DgroupId=org.trie4j -DartifactId=trie4j -Dversion=0.5.0-SNAPSHOT -Dpackaging=jar -DgeneratePom=true
```

Hope you fix this soon, so I can directly you use your repo instead of locally registering a jar on my own :wink: 

Thanks for the wonderful library btw, you saved me lot of time :+1:

**Comment by takawitter** [comment]
Thanks @nopper for reporting issue.
I'm going to move to maven repo.
Please wait a while :)

**Comment by takawitter** [comment]
Now Trie4J is available at Maven Central Repository.
http://search.maven.org/#search%7Cga%7C1%7Ctrie4j

**Comment by nopper** [comment]
I have to buy you a :beer: ;) thanks

**Comment by takawitter** [comment]
I'm looking forward to that :) yw
